### PR TITLE
Added runs.sh to make runnign as jtregs easier

### PR DESCRIPTION
**Pull request by judovana**
Also ignored jtregs artifacts

sh run.sh  /usr/lib/jvm/java
Running with /usr/lib/jvm/java...
XML output  to /home/jvanek/git/ssl-tests/test.1678445012/jdk/JTwork
FAILED: ssl-tests.sh
Passed: ssl-tests-bc-2nd.sh
Passed: ssl-tests-bcfips.sh
Passed: ssl-tests-bcjsse.sh
Passed: ssl-tests-gnutls-client.sh
FAILED: ssl-tests-nss-client.sh
FAILED: ssl-tests-openssl-client.sh
Test results: passed: 4; failed: 3
Report written to /home/jvanek/git/ssl-tests/test.1678445012/jdk/JTreport/html/report.html
Results written to /home/jvanek/git/ssl-tests/test.1678445012/jdk/JTwork
Error: Some tests failed or other problems occurred.

i

### CODE REVIEW

**Comment by zzambers** [comment]
I would have preferred this script in jtreg-wrappers dir. Also, what are the failures?

**Comment by judovana** [comment]
Hmm. see my  second commit here:(  IS ti correct/ If so, it is missing in the crypto tests. wdyt?

**Comment by judovana** [comment]
```
(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at java.base/sun.security.ssl.DHServerKeyExchange$DHServerKeyExchangeMessage.<init>(DHServerKeyExchange.java:152)
	at java.base/sun.security.ssl.DHServerKeyExchange$DHServerKeyExchangeProducer.produce(DHServerKeyExchange.java:481)
	at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1091)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:843)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:802)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:922)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1013)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973)
	at SSLSocketServer.serverLoop(SSLSocketServer.java:133)
	at SSLSocketServer$1.run(SSLSocketServer.java:75)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.InvalidKeyException: The security strength of SHA-1 digest algorithm is not sufficient for this key size
	at java.base/sun.security.provider.DSA.checkKey(DSA.java:124)
	at java.base/sun.security.provider.DSA.engineInitSign(DSA.java:156)
	at java.base/java.security.Signature$Delegate.tryOperation(Signature.java:1308)
	at java.base/java.security.Signature$Delegate.chooseProvider(Signature.java:1257)
	at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1354)
	at java.base/java.security.Signature.initSign(Signature.java:636)
	at java.base/sun.security.ssl.DHServerKeyExchange$DHServerKeyExchangeMessage.getSignature(DHServerKeyExchange.java:435)
	at java.base/sun.security.ssl.DHServerKeyExchange$DHServerKeyExchangeMessage.<init>(DHServerKeyExchange.java:148)
	... 18 more

Mar 10, 2023 3:17:56 PM SSLSocketTester testConfiguration
SEVERE: null
javax.net.ssl.SSLException: Received fatal alert: internal_error
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:340)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at SSLSocketClient.test(SSLSocketClient.java:72)
	at SSLSocketTester.testConfiguration(SSLSocketTester.java:392)
	at SSLSocketTester.testConfigurations(SSLSocketTester.java:322)
	at SSLSocketTester.testProvider(SSLSocketTester.java:234)
	at SSLSocketTester.testProviders(SSLSocketTester.java:190)
	at Main.main(Main.java:30)

Mar 10, 2023 3:17:57 PM SSLSocketServer$1 run
SEVERE: null
```

I guess thats my fedora crypto policies.

**Comment by judovana** [comment]
``` 
 jvanek  jvanek  15:28:40  ~  Desktop  $  update-crypto-policies  --show
LEGACY
```

hmm

**Pull request merged**
